Updated to used the latest rubygems.

diff --git a/wrong_side b/wrong_side
--- a/wrong_side
+++ b/wrong_side
@@ -144,16 +144,16 @@ case $version in
   echo -e "\r\n\r\nGoing to get a fresh ruby-gems...\r\n\r\n"
   cd $HOME
 
-  wget http://rubyforge.org/frs/download.php/60718/rubygems-1.3.5.tgz || { echo "Couldn't download ruby-gems!"; exit 1; } 
+  wget http://rubyforge.org/frs/download.php/69365/rubygems-1.3.6.tgz || { echo "Couldn't download ruby-gems!"; exit 1; } 
 
-  tar -xvf rubygems-1.3.5.tgz || { echo "tar problems"; exit 1; }
-  chmod +x rubygems-1.3.5/setup.rb
+  tar -xvf rubygems-1.3.6.tgz || { echo "tar problems"; exit 1; }
+  chmod +x rubygems-1.3.6/setup.rb
 
-  ruby rubygems-1.3.5/setup.rb
+  ruby rubygems-1.3.6/setup.rb
 
   echo -e "\r\n\r\nCleaning up a little...\r\n\r\n"
-  rm $HOME/rubygems-1.3.5.tgz
-  rm -Rf $HOME/rubygems-1.3.5
+  rm $HOME/rubygems-1.3.6.tgz
+  rm -Rf $HOME/rubygems-1.3.6
 
   ##Create some symlinks so we can use the gem command without whining...
 
