Updated to fix some broken packages.

diff --git a/wrong_side b/wrong_side
--- a/wrong_side
+++ b/wrong_side
@@ -6,14 +6,9 @@
 ## Website: www.dexterchief.com
 ## This is intended to do the heavy lifting to get a working Rails environment from a default Ubuntu install. 
 ##
+aptitude update || { echo "Updating failed! Exiting!"; exit 1; } ;
 
 aptitude install libnotify-bin;
-#libnotify-bin gives us:
-
-#the rest let us use it in ruby:
-#requre 'rubygems'
-#require 'libnotify'
-# Libnotify.show :summary => "Title!", :body => "test"
 
 
 #Get the Ubuntu version that we are running on.
@@ -22,33 +17,22 @@ version=`cat /etc/issue | awk '{print $2}'`; #returns something like '9.10'
 if [ $distro !=  'Ubuntu' ]; then
   echo 'This script is expecting Ubuntu'; exit 1;
 fi
-notify-send "You are running $distro $version";
-
+notify-send "You are running $distro $version" "Downloading and installing now. Sit tight there is a lot to install.";
 
 #
-#Handle the different versions with a case statment so we can deal with different packages if needed. Right now its mostly the same...
+#Handle the different versions with a case statment so we can deal with different packages if needed. 
+#There seems to be a big difference between versions in Alpha and the difference becomes smaller as it gets closer to a final release.
+#This really only here for testing upcoming versions.
+#
 case $version in
 '9.10') #Karmic Koala
 
-  notify-send "Downloading and installing now." "Sit tight there is a lot to install."
-  echo -e "\r\n\r\nDownloading and installing the software...\r\n\r\n"
-  ## aptitude -s = simulate. Great for testing.
-
-  aptitude install --assume-yes build-essential netbeans gedit-plugins vim git-core ruby-full libopenssl-ruby1.8 mysql-server-5.0 mysql-client-5.0 libmysqlclient-dev libsqlite3-dev sqlite3-doc ssl-cert meld python-gtksourceview gitk libxml-ruby1.8 libxslt-ruby1.8 libnotify-ruby libinotify-ruby libgtk2-ruby libnotify-dev || { echo "problem downloading one of the packages"; exit 1; } 
-
-  #ruby-full libopenssl-ruby1.8 
-  #was taken out and replaced with:
-  #ruby1.8 ruby1.8-dev ri1.8 libreadline-ruby1.8 rdoc1.8 libopenssl-ruby1.8 libgdbm-ruby1.8 libdbm-ruby1.8 irb1.8
-  #Explicitly stating what you want is probably a better idea than metapackages especially as versions go by... Still works with Karmic I hope!
+  aptitude install --assume-yes build-essential netbeans gedit-plugins vim git-core ruby-full libopenssl-ruby1.8 mysql-server-5.0 mysql-client-5.0 libmysqlclient-dev libsqlite3-dev sqlite3-doc ssl-cert meld python-gtksourceview gitk libxml2-dev libxslt1-dev libnotify1 libgtk2-ruby || { echo "problem downloading one of the packages"; exit 1; } 
 
 ;;
-'lucid')  ## '10.04') the Alpha version seems not to have a version number yet.
+'lucid')  ## '10.04') the development version seems not to have a version number.
 
-  notify-send "Downloading and installing now." "Sit tight there is a lot to install."
-  echo -e "\r\n\r\nDownloading and installing the software...\r\n\r\n"
-  ## aptitude -s = simulate. Great for testing.
-
-  aptitude install --assume-yes build-essential netbeans gedit-plugins git-core ruby-full libopenssl-ruby1.8 mysql-server-5.0 mysql-client-5.0 libmysqlclient-dev libsqlite3-dev sqlite3-doc ssl-cert gitk libxml-ruby1.8 libxslt-ruby1.8 libnotify-ruby || { echo "problem downloading one of the packages"; exit 1; } 
+  aptitude install --assume-yes build-essential netbeans gedit-plugins git-core ruby-full libopenssl-ruby1.8 mysql-server-5.0 mysql-client-5.0 libmysqlclient-dev libsqlite3-dev sqlite3-doc ssl-cert meld gitk libxml-ruby1.8 libxslt1-dev libxml2-dev libnotify1 || { echo "problem downloading one of the packages"; exit 1; } 
 
 ;;
 *)
@@ -85,14 +69,14 @@ ln -s /usr/bin/irb1.8 /usr/local/bin/irb
 #Rubygems.org/Gemcutter is the place to get all gems now.
 gem install gemcutter
 
-notify-send "Installing gems." "You may want to go have a nap. You may see some errors, but those are just for the documentation so don't worry."
+notify-send "Installing gems." "You may want to go have a nap. You may see some errors, but those are just for the rdocs an won't effect the gems themselves."
 
 #Feel free to add any gems you want here:
 #Will need to think about adding some versions here as well when working on older projects.
 gem install mysql taps heroku haml ruby-debug-ide ruby-debug clickatell mongrel mocha authlogic libnotify activemerchant haml_scaffold jrails nokogiri sanitize mechanize will_paginate nokogiri 
 
 
-notify-send "Installing Ruby on Rails." "Rails 3 beta is the version that is being installed."
+notify-send "Installing Ruby on Rails." "Rails 3 Beta is the version that is being installed."
 #
 #Uncomment the Rails versions you want installed or add others. 
 #They will install side by side and you projects will use the one the need (whatever is specified in the environment.rb).
