Update to make a little more maintainable.

diff --git a/wrong_side b/wrong_side
--- a/wrong_side
+++ b/wrong_side
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 
-##
+                                                                              
 ## Wrong side of the tracks: Rails on Ubuntu
 ## Author: Mike Williamson
-## Website: www.dexterchief.com
+## Website: mikewilliamson.wordpress.com, www.dexterchief.com
 ## This is intended to do the heavy lifting to get a working Rails environment from a default Ubuntu install. 
 ##
 aptitude update || { echo "Updating failed! Exiting!"; exit 1; } ;
@@ -22,17 +22,75 @@ notify-send "You are running $distro $version" "Downloading and installing now. 
 #
 #Handle the different versions with a case statment so we can deal with different packages if needed. 
 #There seems to be a big difference between versions in Alpha and the difference becomes smaller as it gets closer to a final release.
-#This really only here for testing upcoming versions.
 #
 case $version in
-'9.10') #Karmic Koala
+'9.10') 
+  #  _  __                    _        _  __           _       
+  # | |/ /__ _ _ __ _ __ ___ (_) ___  | |/ /___   __ _| | __ _ 
+  # | ' // _` | '__| '_ ` _ \| |/ __| | ' // _ \ / _` | |/ _` |
+  # | . \ (_| | |  | | | | | | | (__  | . \ (_) | (_| | | (_| |
+  # |_|\_\__,_|_|  |_| |_| |_|_|\___| |_|\_\___/ \__,_|_|\__,_|
+  #                                                          
+  #General packages and base Ruby stuff:
+  aptitude install --assume-yes build-essential openjdk-6-jre gedit-plugins vim ruby-full libopenssl-ruby1.8 ssl-cert meld python-gtksourceview || { notify-send "Problem downloading one of the main packages"; exit 1; } 
 
-  aptitude install --assume-yes build-essential netbeans gedit-plugins vim git-core ruby-full libopenssl-ruby1.8 mysql-server-5.0 mysql-client-5.0 libmysqlclient-dev libsqlite3-dev sqlite3-doc ssl-cert meld python-gtksourceview gitk libxml2-dev libxslt1-dev libnotify1 libgtk2-ruby || { echo "problem downloading one of the packages"; exit 1; } 
+  #Git:
+  aptitude install --assume-yes git-core gitk || { notify-send "Problem installing Git"; } 
 
+  #required by Mysql gem:
+  aptitude install --assume-yes mysql-server-5.0 mysql-client-5.0 libmysqlclient-dev || { echo "Problem installing Mysql"; exit 1; } 
+
+  #Postgres
+  #uncomment the line below and at some point aftwards run "sudo gem install pg":
+  #aptitude install postgresql postgresql-server-dev-8.4 || { echo "problem downloading one of the packages"; exit 1; } 
+
+  #required by the Nokogiri gem:
+  aptitude install --assume-yes libxml2-dev libxslt1-dev|| { notify-send "Problem installing packages." "Nokogiri and the gems that depend on it (sanitize and mechanize) will be broken."; } 
+
+  #Required by libnotify gem:
+  aptitude install --assume-yes libnotify1 || { notify-send "Problem installing libnotify"; } 
+
+  #Required by Heroku/Taps gem:
+  aptitude install --assume-yes libsqlite3-dev sqlite3-doc  || { notify-send "Problem installing Sqlite." "Taps gem will fail."; } 
+
+  #RMagick gem:
+  #uncomment the line below if you want to use RMagick. You will also need to run "sudo gem install rmagick" later as well.
+  #aptitude install imagemagick librmagick-ruby libmagickwand-dev
+  
 ;;
-'10.04')  ## '10.04') the development version seems not to have a version number.
+'10.04')
+  # _                _     _   _                      
+  #| |    _   _  ___(_) __| | | |    _   _ _ __ __  __
+  #| |   | | | |/ __| |/ _` | | |   | | | | '_ \\ \/ /
+  #| |___| |_| | (__| | (_| | | |___| |_| | | | |>  < 
+  #|_____|\__,_|\___|_|\__,_| |_____|\__, |_| |_/_/\_\
+  #                                   |___/            
+  #
+  #Some basics and the Ruby stuff:
+  aptitude install --assume-yes build-essential gedit-plugins ruby-full openjdk-6-jre libopenssl-ruby1.8 ssl-cert meld  || { echo "Problem downloading one of the main packages."; exit 1; } 
 
-  aptitude install --assume-yes build-essential gedit-plugins git-core ruby-full openjdk-6-jre libopenssl-ruby1.8 mysql-server-5.1 mysql-client-5.1 libmysqlclient-dev libsqlite3-dev sqlite3-doc ssl-cert meld gitk libxml-ruby1.8 libxslt1-dev libxml2-dev libnotify1 || { echo "problem downloading one of the packages"; exit 1; } 
+  #Git:
+  aptitude install --assume-yes git-core gitk || { notify-send "Problem installing Git"; } 
+
+  #Required by Mysql gem:
+  aptitude install --assume-yes  mysql-server-5.1 mysql-client-5.1 libmysqlclient-dev  || { notify-send "Problem installing Mysql"; exit 1; } 
+
+  #Postgres
+  #uncomment the line below and at some point aftwards run "sudo gem install pg":
+  #aptitude install postgresql postgresql-server-dev-8.4 || { echo "problem downloading one of the packages"; exit 1; } 
+
+  #Required by Nokogiri gem:
+  aptitude install --assume-yes  libxml-ruby1.8 libxslt1-dev libxml2-dev  || { notify-send "Problem installing packages." "Nokogiri and the gems that depend on it (sanitize and mechanize) will be broken."; } 
+
+  #Required by Heroku/Taps gem:
+  aptitude install --assume-yes libsqlite3-dev sqlite3-doc  || { notify-send "Problem installing Sqlite." "Taps gem will fail."; } 
+
+  #Required by libnotify gem:
+  aptitude install --assume-yes libnotify1 || { notify-send "Problem installing libnotify"; } 
+
+  #RMagick gem:
+  #uncomment the line below if you want to use RMagick. You will also need to run "sudo gem install rmagick" later as well.
+  #aptitude install imagemagick librmagick-ruby libmagickwand-dev
 
 ;;
 *)
@@ -44,6 +102,12 @@ esac
 #The rest if the install is the same for both versions...
 #
 
+# _   _      _   _                          
+#| \ | | ___| |_| |__   ___  __ _ _ __  ___ 
+#|  \| |/ _ \ __| '_ \ / _ \/ _` | '_ \/ __|
+#| |\  |  __/ |_| |_) |  __/ (_| | | | \__ \
+#|_| \_|\___|\__|_.__/ \___|\__,_|_| |_|___/
+#
 #cd somewhere reasonable
 cd $HOME
 notify-send "Downloading Netbeans 6.9 Beta." "6.8 Dosen't support Rails 3 so we are grabbing 6.9 from the netbeans site.";
@@ -57,19 +121,26 @@ su $SUDO_USER -c './netbeans-6.9beta-ml-ruby-linux.sh --silent'
 
 
 
+# ____        _            ____                    
+#|  _ \ _   _| |__  _   _ / ___| ___ _ __ ___  ___ 
+#| |_) | | | | '_ \| | | | |  _ / _ \ '_ ` _ \/ __|
+#|  _ <| |_| | |_) | |_| | |_| |  __/ | | | | \__ \
+#|_| \_\\__,_|_.__/ \__, |\____|\___|_| |_| |_|___/
+#                    |___/                          
+
 notify-send "Going to get a fresh ruby-gems." "Downloading the latest version from rubyforge."
 echo -e "\r\n\r\nGoing to get a fresh ruby-gems...\r\n\r\n"
 cd $HOME
-wget http://rubyforge.org/frs/download.php/69365/rubygems-1.3.6.tgz || { echo "Couldn't download ruby-gems!"; exit 1; } 
+wget http://rubyforge.org/frs/download.php/70696/rubygems-1.3.7.tgz || { echo "Couldn't download ruby-gems!"; exit 1; } 
 
-tar -xvf rubygems-1.3.6.tgz || { echo "tar problems"; exit 1; }
-chmod +x rubygems-1.3.6/setup.rb
+tar -xvf rubygems-1.3.7.tgz || { echo "tar problems"; exit 1; }
+chmod +x rubygems-1.3.7/setup.rb
 
-ruby rubygems-1.3.6/setup.rb
+ruby rubygems-1.3.7/setup.rb
 
 echo -e "\r\n\r\nCleaning up a little...\r\n\r\n"
-rm $HOME/rubygems-1.3.6.tgz
-rm -Rf $HOME/rubygems-1.3.6
+rm $HOME/rubygems-1.3.7.tgz
+rm -Rf $HOME/rubygems-1.3.7
 
 ##Create some symlinks so we can use the gem command without whining...
 
@@ -83,12 +154,18 @@ gem update --system
 #Rubygems.org/Gemcutter is the place to get all gems now.
 gem install gemcutter
 
+
+
+
+
 notify-send "Installing gems." "You may want to go have a nap. You may see some errors, but those are just for the rdocs an won't effect the gems themselves."
 
 #Feel free to add any gems you want here:
 #Will need to think about adding some versions here as well when working on older projects.
 gem install mysql taps heroku haml ruby-debug-ide ruby-debug clickatell mongrel mocha authlogic libnotify activemerchant haml_scaffold jrails nokogiri sanitize mechanize will_paginate nokogiri 
 
+#gem install pg
+#gem install rmagick
 
 notify-send "Installing Ruby on Rails." "Rails 3 Beta is the version that is being installed."
 #
